state_list = [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
    "Distrito Federal",
]

city_list = [
    {"name": "Rio de Janeiro", "state": "Rio de Janeiro"},
    {"name": "São Paulo", "state": "São Paulo"},
    {"name": "Petrópolis", "state": "Rio de Janeiro"},
    {"name": "Rio de Contas", "state": "Bahia"},
    {"name": "Nova Friburgo", "state": "Rio de Janeiro"},
    {"name": "Iconha", "state": "Espírito Santo"},
    {"name": "Caraguatatuba", "state": "São Paulo"},
    {"name": "Angra dos Reis", "state": "Rio de Janeiro"},
    {"name": "Coronel Fabriciano", "state": "Minas Gerais"},
    {"name": "Niterói", "state": "Rio de Janeiro"},
    {"name": "Nilópolis", "state": "Rio de Janeiro"},
    {"name": "Magé", "state": "Rio de Janeiro"},
    {"name": "Jaraguá do Sul", "state": "Santa Catarina"},
    {"name": "Ipatinga", "state": "Minas Gerais"},
    {"name": "Vitória", "state": "Espírito Santo"},
    {"name": "São José do Rio Pardo", "state": "São Paulo"},
    {"name": "São José dos Campos", "state": "São Paulo"},
]
