"""remove title and text columns from 'messages' table. Set a default value to date column

Revision ID: 15daa7e61f40
Revises: c994f1b1ed8a
Create Date: 2022-05-03 20:27:38.623570

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "15daa7e61f40"
down_revision = "c994f1b1ed8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "title")
    op.drop_column("messages", "text")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "messages",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
