"""rename 'messages' table to 'message_logs'. Change 'users_messages' foreignkey

Revision ID: 4785f95a9c8f
Revises: 15daa7e61f40
Create Date: 2022-05-03 23:14:36.435425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4785f95a9c8f"
down_revision = "15daa7e61f40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "users_messages_message_id_fkey", "users_messages", type_="foreignkey"
    )
    op.drop_table("messages")
    op.create_table(
        "message_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        None, "users_messages", "message_logs", ["message_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_messages", type_="foreignkey")
    op.create_foreign_key(
        "users_messages_message_id_fkey",
        "users_messages",
        "messages",
        ["message_id"],
        ["id"],
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="messages_pkey"),
    )
    op.drop_table("message_logs")
    # ### end Alembic commands ###
