"""add uf column in 'states' table

Revision ID: 9012aed443a3
Revises: f3042e2da0c8
Create Date: 2022-05-04 10:44:23.484836

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9012aed443a3"
down_revision = "f3042e2da0c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("states", sa.Column("uf", sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("states", "uf")
    # ### end Alembic commands ###
