"""set unique to true in title column from 'risks' table

Revision ID: c994f1b1ed8a
Revises: f06d8f324633
Create Date: 2022-05-02 21:39:54.852930

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c994f1b1ed8a"
down_revision = "f06d8f324633"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "risks", ["title"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "risks", type_="unique")
    # ### end Alembic commands ###
