"""add password_hash column to 'user' model

Revision ID: f06d8f324633
Revises: 17bacef08c94
Create Date: 2022-04-30 14:05:30.874476

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f06d8f324633"
down_revision = "17bacef08c94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
